service: project-gc-society

custom:
  secrets: ${file(secrets.json)}

provider:
  name: aws
  iamRoleStatements:
  - Effect: 'Allow'
    Action:
      - s3:GetBucketLocation
      - s3:GetObject
      - s3:ListBucket
      - s3:ListBucketMultipartUploads
      - s3:ListMultipartUploadParts
      - s3:AbortMultipartUpload
      - s3:CreateBucket
      - s3:PutObject
    Resource:
      - arn:aws:s3:::gautam-chaulagain-asset
      - arn:aws:s3:::gautam-chaulagain-asset/*
  runtime: nodejs8.10
  timeout: 30
  stage: ${self:custom.secrets.NODE_ENV}
  environment: 
    NODE_ENV: ${self:custom.secrets.NODE_ENV}
    DB_NAME: ${self:custom.secrets.DB_NAME}
    DB_USER: ${self:custom.secrets.DB_USER}
    DB_PASSWORD: ${self:custom.secrets.DB_PASSWORD}
    DB_HOST: ${self:custom.secrets.DB_HOST}
    DB_PORT: ${self:custom.secrets.DB_PORT}
  vpc:
    securityGroupIds:
      - ${self:custom.secrets.SECURITY_GROUP_ID}
      - ${self:custom.secrets.SECURITY_GROUP_ID_OPEN}
    subnetIds:
      - ${self:custom.secrets.SUBNET1_ID}
      - ${self:custom.secrets.SUBNET2_ID}
      - ${self:custom.secrets.SUBNET3_ID}

functions:
  healthCheck:
    handler: handler.healthCheck
    events:
      - http:
          path: /
          method: get
          cors: true
  create:
    handler: handler.create
    events:
      - http:
          path: members
          method: post
          cors: true
  getOne:
    handler: handler.getOne
    events:
      - http:
          path: members/{memberId}
          method: get
          cors: true
  getAll:
    handler: handler.getAll
    events:
     - http:
         path: members
         method: get
         cors: true
  update:
    handler: handler.update
    events:
     - http:
         path: members/{memberId}
         method: put
         cors: true
  destroy:
    handler: handler.destroy
    events:
     - http:
         path: members/{memberId}
         method: delete
         cors: true
  fileUpload:
    handler: fileHandler.getPresignedPostData
    events:
    - http:
        path: fileUpload
        method: post
        cors: true

plugins:
  - serverless-offline